---
version: '3.4'

services:
  authentik-ldap-outpost:
    image: ghcr.io/goauthentik/ldap:$AUTHENTIK_TAG
    restart: unless-stopped
    env_file:
      - secret.env
    environment:
      AUTHENTIK_HOST: https://authentik-server:9433
    ports:
      - 389:3389
      - 636:6636
    networks:
      - authentik
networks:
  authentik:
    name: authentik
