---
version: '3.4'

services:
  authentik_ldap_outpost:
    image: ghcr.io/goauthentik/ldap:$AUTHENTIK_TAG
    restart: unless-stopped
    environment:
      AUTHENTIK_HOST: http://authentik_server:$AUTHENTIK_LDAP__HOST_PORT
      AUTHENTIK_HOST_BROWSER: $AUTHENTIK_LDAP__HOST_BROWSER:$AUTHENTIK_LDAP__HOST_PORT
      AUTHENTIK_INSECURE: 'true'
      AUTHENTIK_TOKEN: $AUTHENTIK_LDAP__TOKEN
    ports:
      - 389:3389
      - 636:6636
    networks:
      - authentik
networks:
  authentik:
    name: authentik
