---
version: '3.4'

services:
  authentik_ldap_outpost:
    image: ghcr.io/goauthentik/ldap:$AUTHENTIK_TAG
    restart: unless-stopped
    environment:
      AUTHENTIK_HOST: $AUTHENTIK_LDAP__HOST
      AUTHENTIK_INSECURE: false
      AUTHENTIK_TOKEN: $AUTHENTIK_LDAP__TOKEN
    ports:
      - 389:3389
      - 636:6636
    networks:
      - authentik
networks:
  authentik:
    name: authentik
    external: true
