---
version: '3.4'

services:
  authentik_postgresql:
    image: postgres:12-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - authentik_database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$PG_DB
      - POSTGRES_PASSWORD=$PG_PASS
      - POSTGRES_USER=$PG_USER
    env_file:
      - .env
  authentik_redis:
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
  authentik_media_chown:
    image: privatebin/chown:1.34.1-musl-1.2.2-r3
    read_only: true
    command: 1000:1000 /mnt
    volumes:
      - authentik_media:/mnt
  authentik_server:
    image: ghcr.io/goauthentik/server:$AUTHENTIK_TAG
    restart: unless-stopped
    depends_on:
      - authentik_media_chown
    command: server
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik_postgresql
      AUTHENTIK_POSTGRESQL__NAME: $PG_DB
      AUTHENTIK_POSTGRESQL__PASSWORD: $PG_PASS
      AUTHENTIK_POSTGRESQL__USER: $PG_USER
      AUTHENTIK_REDIS__HOST: authentik_redis
      # AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
      # WORKERS: 2
    env_file:
      - .env
    volumes:
      - ./mounts/custom_templates/:/templates
      - authentik_geoip:/geoip
      - authentik_media:/media
    ports:
      - "0.0.0.0:$AUTHENTIK_PORT_HTTP:9000"
      - "0.0.0.0:$AUTHENTIK_PORT_HTTPS:9443"
    networks:
      - authentik
      - default
  authentik_worker:
    image: ghcr.io/goauthentik/server:$AUTHENTIK_TAG
    restart: unless-stopped
    depends_on:
      - authentik_media_chown
    command: worker
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik_postgresql
      AUTHENTIK_POSTGRESQL__NAME: $PG_DB
      AUTHENTIK_POSTGRESQL__PASSWORD: $PG_PASS
      AUTHENTIK_POSTGRESQL__USER: $PG_USER
      AUTHENTIK_REDIS__HOST: authentik_redis
      # AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
    env_file:
      - .env
    # This is optional, and can be removed. If you remove this, the following will happen
    # - The permissions for the /media folders aren't fixed, so make sure they are 1000:1000
    # - The docker socket can't be accessed anymore
    #user: root
    volumes:
      - ./mounts/custom_templates/:/templates
      #- /var/run/docker.sock:/var/run/docker.sock
      - authentik_geoip:/geoip
      - authentik_media:/media
      - npm_letsencrypt:/certs
  authentik_geoipupdate:
    image: maxmindinc/geoipupdate:v4.9
    restart: unless-stopped
    volumes:
      - authentik_geoip:/usr/share/GeoIP
    environment:
      GEOIPUPDATE_EDITION_IDS: "GeoLite2-City"
      GEOIPUPDATE_FREQUENCY: "8"
    env_file:
      - .env
volumes:
  authentik_database:
    driver: local
  authentik_geoip:
    driver: local
  authentik_media:
    driver: local
  npm_letsencrypt:
    driver: local
networks:
  authentik:
    name: authentik
