---
version: '3.4'

services:
  cloudflared_chown:
    # https://github.com/cloudflare/cloudflared/issues/163
    image: privatebin/chown:1.34.1-musl-1.2.2-r3
    read_only: true
    command:
      - 65532:65532
      - /mnt
    volumes:
      - cloudflared_certs:/mnt
  
  cloudflared:
    image: cloudflare/cloudflared:$CLOUDFLARED_TAG
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    volumes:
      - ./mounts/cloudflared/:/etc/cloudflared
      - cloudflared_certs:/home/nonroot/.cloudflared/
    networks:
      - cloudflared
volumes:
  cloudflared_certs:
    driver: local
networks:
  cloudflared:
    name: cloudflared
