---
version: '3.4'

services:
  cloudflared:
    image: cloudflare/cloudflared:$CLOUDFLARED_TAG
    restart: unless-stopped
    entrypoint: /usr/local/bin/cloudflared
    command: tunnel --no-autoupdate run
    volumes:
      - ./volumes/cloudflared/:/etc/cloudflared
      - cloudflared_certs:/home/nonroot/.cloudflared/:rw
    networks:
      - cloudflared
volumes:
  cloudflared_certs:
    driver: local
networks:
  cloudflared:
    name: cloudflared
