---
version: '3.4'

services:
  cloudflared:
    image: cloudflare/cloudflared:$CLOUDFLARED_TAG
    restart: unless-stopped
    #command: /usr/local/bin/cloudflared tunnel --no-autoupdate run
    entrypoint: /usr/local/bin/cloudflared
    command: tunnel --no-autoupdate run
    volumes:
      - ./volumes/cloudflared/:/etc/cloudflared
    networks:
      - cloudflared
networks:
  cloudflared:
    name: cloudflared
